language: r
r:
 - 3.4.0
 - devel
cache: packages
sudo: false
warnings_are_errors: true
r_check_args: --as-cran
   
git:
  depth: 5
  
r_packages:
# Current devtools binary too new for R 3.4.0
  - devtools
 - ape
 - covr
 - memoise
 - phangorn
 - R.cache
 - Rdpack
 - roxygen2
 - testthat

before_script:
 - R -e "devtools::document()"
  
after_success:
  - Rscript -e "covr::codecov()"
  