language: r
r:
 - 3.4.0
 - release
 - devel
cache: packages
sudo: required # required if r_binary_packages; false otherwise
warnings_are_errors: true
r_check_args: --as-cran
   
git:
  depth: 5

before_script:
 - R -e "devtools::document()"
  
after_success:
  - Rscript -e "covr::codecov()"
  