language: r
r:
 - 3.4.0
 - devel
cache: packages
warnings_are_errors: false
#r_github_packages: KlausVigo/phangorn
   
git:
  depth: 5

r_packages:
 - devtools
 - roxygen2
 - testthat
 - covr
   
install:
 - R -e "install.packages('devtools')"
 - R -e "install.packages('ape')"
 - R -e "devtools::install_github('KlausVigo/phangorn', ref='7192bfb4403c35c16a7b735160525d272736b061')"
 - R -e "install.packages('testthat')"
 - R -e "install.packages('roxygen2')"
 - R -e "devtools::document()"

# Needed for phangorn install?  
bioc_required: true
bioc_packages:
  - seqLogo
  - Biostrings
  
  
after_success:
  - Rscript -e 'library(covr); codecov()'