language: r
r:
 - 3.4.0
 - devel
cache: packages
sudo: required
warnings_are_errors: true
r_check_args: --as-cran
   
git:
  depth: 5

r_binary_packages:
 - ape
 - covr
 - memoise
 - phangorn
 - R.cache
 - Rdpack
 - roxygen2
 - testthat
 
r_packages:
# Can't use current devtools on R 3.4.0
 - devtools

before_script:
 - R -e "devtools::document()"
  
after_success:
  - Rscript -e "covr::codecov()"
  