language: r
r:
 - 3.4.0
 - devel
cache: packages
warnings_are_errors: true
r_check_args: --as-cran
   
git:
  depth: 5

r_binary_packages:
 - testthat
  
r_packages:
 - covr
 - devtools
 - memoise
 - phangorn
 - R.cache
 - roxygen2
 - testthat
   
before_script:
 - R -e "devtools::document()"
  
after_success:
  - Rscript -e "covr::codecov()"
  